name: regressio tests
on: [push, pull_request]
jobs:
  regressio-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib pytest
    - name: Pytests
      run: |
        pytest